[theme]
primaryColor = "#3b82f6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#1f2937"
font = "sans serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false